name: ama-logicapp-ci

trigger:
  branches:
    include:
      - lab-ama

pool:
  vmImage: windows-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'src/MyLogicApp/Templates'
    Contents: '*.json'  
    TargetFolder: '$(Pipeline.Workspace)/Resources'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/Resources'
    artifact: 'Resources'
    publishLocation: 'pipeline'