parameters:
- name: environment
  displayName: Specific Environment
  type: string
  default: Default
  values:
  - Default  
  - Prd

name: $(Build.DefinitionName)-$(Build.BuildId)

pool:
  vmImage: windows-2022

trigger: none

pr: none

resources:
  pipelines:
    - pipeline: BuildPipeline
      source: %ProjectName%.build
      trigger: 
        branches:
          include: 
          - main
          - feature/*

extends: 
  template: solution.yml
  parameters:
    config: 
      basePath: .%BasePath%    
      isBuild: false
      isDeploy: true
      environment: ${{parameters.environment}} 